name: Bug Report
description: Report a bug or issue with the template
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Actually...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      value: |
        - OS: [e.g., Ubuntu 22.04, macOS 13.0]
        - Node Version: [e.g., 18.17.0]
        - npm/pnpm Version: [e.g., 9.0.0]
        - Astro Version: [e.g., 4.16.0]
        - Browser (if applicable): [e.g., Chrome 120, Firefox 121]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, paste any error messages or logs
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any other relevant information...

  - type: checkboxes
    id: privacy
    attributes:
      label: Privacy Check
      description: Please confirm the following
      options:
        - label: I have removed any sensitive information from this report
          required: true
        - label: This is not a security vulnerability (see SECURITY.md for security issues)
          required: true
